import type { Metadata } from "next";
import { Gluten } from "next/font/google";
import "./globals.scss";
import { CSSProperties } from "react";
import Header from "./components/Header";
import LocalFont from "next/font/local";
import Footer from "./components/footer/Footer";

const lt = LocalFont({
  src: [
    {
      path: "/fonts/LTKaraoke-Light.ttf",
      weight: "300",
      style: "Light",
    },
    {
      path: "/fonts/LTKaraoke-Regular.ttf",
      weight: "400",
      style: "Regular",
    },
    {
      path: "/fonts/LTKaraoke-Medium.ttf",
      weight: "500",
      style: "Medium",
    },
    {
      path: "/fonts/LTKaraoke-Bold.ttf",
      weight: "700",
      style: "Bold",
    },
  ],
});

const gluten = Gluten({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "HeartSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={""}
        style={
          {
            "--fontL": lt.style.fontFamily,
            "--fontG": gluten.style.fontFamily,
          } as CSSProperties
        }
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
